version: '3.5'

services:
  db:
    image: postgres
    env_file:
      - .env
    container_name: postgres
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1GB
        reservations:
          cpus: "2"
          memory: 1GB

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - db
